### ISSUE TITLE
Create the repos for the projects

### ISSUE THREAD

**Issue by brucellino** [AAROC/e-Research-Hackfest-prep#10]
The repositories for the projects need to be created. This has to be done once the projects have been defined. 

Repository name will be the same as project name.

**Comment by brucellino** [comment]
So, apparently, if the user already exists, you get a 404. I need to have a check on the users first, and probably the repos too.

**Comment by brucellino** [comment]
@cudanor can you please confirm whether the repos have been created ?

**Comment by brucellino** [comment]
Ok, still need to add ACLs to the repos.

**Comment by cudanor** [comment]
Working on it. Get back to you shortly.

Thanks

**Comment by cudanor** [comment]
Hello Bruce,

curl  -X POST \

  -H "Authorization: $TOKEN" \

  -H "Content-Type: application/json" \

  -d '{

          "name": “Plantisc”

      }' \

  https://glibrary.ct.infn.it:3500/v2/repos


I get unexpected token error when trying to create the repo Plantisc with
the above script.

**Comment by cudanor** [comment]
I can't seem to find the command in the tutorial to lookup individual (entity) repos in gLibrary. Please assist.
Thanks

**Comment by cudanor** [comment]
When I login into gLibrary and export my Token, does the token expire if I close my console and re-open it? Just wondering.

Thanks

**Comment by brucellino** [comment]
the token gives a TTL - that's part of the response. So, if you try again before the token expires, that's fine.  even from somewhere else.

**Comment by cudanor** [comment]
What is the lifespan of the token? Where is cached? Is it in my machine or in the gLibrary server?

The first issue has not been addressed yet. That is, being able to see my individual repos.

Thanks

**Comment by brucellino** [comment]
ok, @cudanor After double-checking you're right - the repo `Plantisc2` has not yet been created. I'm not sure why. 

Can you open a new issue for the gLibrary token- I'd like to deal with that in a separate issue.

**Comment by cudanor** [comment]
Regarding the authentication token, I am asking where it is stored. In machine or in the gLibrary server? and how long does it live? If I close my console does it expire?

Thanks

**Comment by brucellino** [comment]
Thanks @cudanor - I need  you to open a new issue (https://github.com/AAROC/e-Research-Hackfest-prep/issues/new) with that question - it's a different issue :)

**Comment by cudanor** [comment]
I've done that.
Thanks

**Comment by brucellino** [comment]
@cudanor the repositories have been created. I'm going to see if you have rights to create collections
