### ISSUE TITLE
Regarding gLibrary token

### ISSUE THREAD

**Issue by cudanor** [AAROC/e-Research-Hackfest-prep#11]
Regarding the authentication token, I am asking where it is stored. In machine or in the gLibrary server? and how long does it live? If I close my console does it expire?

Thanks

**Comment by brucellino** [comment]
Hi @cudanor thanks for the question.

The token returned back to you from curl _only_ lives persistently on the gLibrary server. If you don't save it  on the client (the shell where you're interacting with gLibrary, or the application that's using gLibrary), it will be lost. I think in your case you may have put it in an environment variable (`export AUTH=` ) but that is lost when you exit the shell.

**Comment by cudanor** [comment]
Yes I exported it to an environment variable.

Thanks

**Comment by cudanor** [comment]
I get error 401 when I run this:
curl -H "Authorization: $TOKEN" \
  https://glibrary.ct.infn.it:3500/v2/repos/

The same with this one also:
curl  -X POST \
  -H "Authorization: $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{
          "name": "plantisc2"
      }' \
  https://glibrary.ct.infn.it:3500/v2/repos

**Comment by brucellino** [comment]
Yes, that path is to CREATE a repo - but your user (`cudanor`) doesn't have the rights to do that. You can only create entities or collections in your repo.

**Comment by cudanor** [comment]
I have tried viewing the repo plantisc2 and creating collections treatment but none of my commands worked. It returned the error, " you are not allowed to access this collections"

What else do I do? Nothing seems to work.

Thanks

**Comment by brucellino** [comment]
Ok - this is again a different problem :smile: - Can you create a new issue with the permission denied issue ?

Thanks !
