### ISSUE TITLE
Unable to login into gLibrary

### ISSUE THREAD

**Issue by cudanor** [AAROC/e-Research-Hackfest-prep#12]
I do not know why gLibrary has refused logging me in. It throws token error. But I was able to login in the morning.
Even now I can still login with demouser, but not with cudanor. I have cross-checked the script and it is Ok.

Thanks

**Comment by brucellino** [comment]
What error code is it giving you ? 400 ?

**Comment by brucellino** [comment]
I'm not able to reproduce this - I can log in with your credentials fine. Temporary network issue ?
