### ISSUE TITLE
Unable to create collections

### ISSUE THREAD

**Issue by cudanor** [AAROC/e-Research-Hackfest-prep#13]
I have tried viewing the repo plantisc2 and creating collections treatment but none of my commands worked. It returned the error, " you are not allowed to access this collections"

What else do I do? Nothing seems to work.

Thanks

**Comment by brucellino** [comment]
Hi @cudanor thanks, I was able to reproduce the problem. The repo has been created, but the ACLs not set. I'm looking into why... in the meantime, I've set the ACL by hand so that you can read and write data into the repo.

**Comment by cudanor** [comment]
Success! Collection and ACL created.
