### ISSUE TITLE
Unable to list Plantisc2 repo

### ISSUE THREAD

**Issue by cudanor** [AAROC/e-Research-Hackfest-prep#14]
curl  -H "Authorization: $TOKEN" \
  https://glibrary.ct.infn.it:3500/v2/repos/plantisc2/

returns error 401 - Authorization required.

**Comment by brucellino** [comment]
hi @cudanor - sorry, can we move this issue to the [warmups](https://github.com/AAROC/hackfest-warmups) please - this is related to the warmup exercises. just create the same issue there  - https://github.com/AAROC/hackfest-warmups/issues/new
