### ISSUE TITLE
How to create an Open Stack tenant for the event

### ISSUE THREAD

**Issue by brucellino** [AAROC/e-Research-Hackfest-prep#30]
@mtorrisi  We need a quick description of how to create an open stack tenant for the event, so that the dev, ci and practice machines can be deployed into it.

**Comment by brucellino** [comment]
bumping @mtorrisi - you mentioned that there was a script for this. has it been committed ?

**Comment by mtorrisi** [comment]
Sorry for the delay is here: https://gist.github.com/d445e4dc25b0aaf52aa0f8551745c2e1.git
