### ISSUE TITLE
Error perfroming playbook

### ISSUE THREAD

**Issue by mtorrisi** [AAROC/e-Research-Hackfest-prep#83]
Running plabook with:
`ansible-playbook development-environment.yml -i ../../inventory/sgw-dev  --extra-vars "site_name=addis-hackfest slack_token=1234"`

I get:
```TASK [Announce the setup] ******************************************************
fatal: [sgw-dev.sci-gaia.eu]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to sgw-dev.sci-gaia.eu closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE"}
```

If comment the `Announce the setup` task I get 
```TASK [Low down dirty setup] ****************************************************
fatal: [sgw-dev.sci-gaia.eu]: FAILED! => {"failed": true, "msg": "'managed_prerequisites' is undefined"```

**Comment by brucellino** [comment]
This looks like it's because there's a missing python installation. That's one of the prerequisites of Ansible. Let me take a look...

**Comment by mtorrisi** [comment]
I supposed this was the problem, so I tried to install python2.7 on target machine manually, but I got the same error

**Comment by brucellino** [comment]
Don't worry. I'm fixing it upstream.
